apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: easyfunding-project
  namespace: argocd
spec:
  description: 'Easyfunding Project'
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
